// R7 Question Bank — 20 Topics, 340+ Questions
// Each question has: q, options, answer (index), difficulty (1-4), fact

const QUESTIONS = {
  "General Knowledge": [
    { q: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2, difficulty: 1, fact: "The Pacific covers more area than all landmasses combined — about 165.25 million sq km." },
    { q: "How many bones are in the adult human body?", options: ["186", "206", "216", "226"], answer: 1, difficulty: 1, fact: "Babies are born with ~270 bones. Many fuse together, leaving adults with 206." },
    { q: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: 1, difficulty: 1, fact: "Mars appears red because its surface is covered in iron oxide — the planet is literally rusting." },
    { q: "What is the hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: 2, difficulty: 1, fact: "Diamond is hardest but not toughest — it can shatter on impact. Jade is actually tougher." },
    { q: "Which country has the most time zones?", options: ["Russia", "USA", "France", "China"], answer: 2, difficulty: 3, fact: "France has 12 time zones thanks to overseas territories, beating Russia's 11." },
    { q: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], answer: 1, difficulty: 2, fact: "Vatican City is just 0.44 sq km — walkable in about 20 minutes." },
    { q: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: 2, difficulty: 1, fact: "At night, plants actually release CO₂ and absorb oxygen — reversing the daytime process." },
    { q: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2, difficulty: 2, fact: "Canberra was a compromise — Sydney and Melbourne couldn't agree, so they built a new city between them." },
    { q: "Which element has the symbol 'Au'?", options: ["Silver", "Gold", "Aluminum", "Argon"], answer: 1, difficulty: 2, fact: "All the gold ever mined would fit into about 3.5 Olympic swimming pools." },
    { q: "What is the only letter not in any US state name?", options: ["Q", "X", "Z", "B"], answer: 0, difficulty: 3, fact: "Every letter appears in at least one state name — except Q." },
    { q: "Which organ consumes the most energy?", options: ["Heart", "Liver", "Brain", "Lungs"], answer: 2, difficulty: 2, fact: "The brain uses 20% of body energy despite being only 2% of body weight." },
    { q: "How many hearts does an octopus have?", options: ["1", "2", "3", "4"], answer: 2, difficulty: 2, fact: "Two hearts pump blood to gills; the third pumps it to the body. The blood is blue because it uses copper." },
    { q: "What is the most spoken language in the world?", options: ["English", "Spanish", "Mandarin", "Hindi"], answer: 2, difficulty: 2, fact: "Mandarin has over 920 million native speakers. English leads in total speakers including non-native." },
    { q: "Which country has the longest coastline?", options: ["Australia", "Indonesia", "Canada", "Russia"], answer: 2, difficulty: 3, fact: "Canada's coastline is 202,080 km — if you walked 20km/day, it would take 27 years to complete." },
    { q: "Which blood type is the universal donor?", options: ["A+", "B+", "AB+", "O-"], answer: 3, difficulty: 2, fact: "Only about 7% of people have O- blood, making it perpetually in short supply at blood banks." },
    { q: "What is the driest continent on Earth?", options: ["Africa", "Australia", "Antarctica", "Asia"], answer: 2, difficulty: 3, fact: "Antarctica gets less precipitation than the Sahara. Its interior is technically the world's largest desert." },
    { q: "How many teeth does an adult human have?", options: ["28", "30", "32", "34"], answer: 2, difficulty: 1, fact: "32 including wisdom teeth. About 35% of people are born without wisdom teeth." },
    { q: "What percentage of Earth's water is freshwater?", options: ["3%", "10%", "25%", "50%"], answer: 0, difficulty: 3, fact: "Only 3% is fresh, and 2/3 of that is frozen in glaciers." },
    { q: "Which country gifted the Statue of Liberty to the USA?", options: ["UK", "France", "Germany", "Italy"], answer: 1, difficulty: 1, fact: "France gifted it in 1886. It arrived in 350 individual pieces packed in 214 crates." },
    { q: "What is the rarest blood type?", options: ["O-", "A-", "B-", "AB-"], answer: 3, difficulty: 4, fact: "AB- occurs in less than 1% of the population." },
    { q: "How many time zones does China officially use?", options: ["1", "3", "5", "8"], answer: 0, difficulty: 4, fact: "Despite spanning 5 geographical time zones, China uses only one — Beijing Time." },
  ],
  "Marvel / MCU": [
    { q: "What is the name of Thor's hammer?", options: ["Stormbreaker", "Mjolnir", "Gungnir", "Hofund"], answer: 1, difficulty: 1, fact: "The filming prop weighed about 12 lbs." },
    { q: "Which Infinity Stone is hidden on Vormir?", options: ["Time", "Soul", "Mind", "Power"], answer: 1, difficulty: 2, fact: "The Soul Stone's location was Marvel's best-kept secret." },
    { q: "Who killed Tony Stark's parents?", options: ["Red Skull", "Loki", "Winter Soldier", "Ultron"], answer: 2, difficulty: 2, fact: "Howard's last word was 'Sergeant Barnes?'" },
    { q: "What is Wakanda's most valuable resource?", options: ["Adamantium", "Uru", "Vibranium", "Palladium"], answer: 2, difficulty: 1, fact: "Vibranium arrived via meteorite 10,000 years ago." },
    { q: "How many Infinity Stones are there?", options: ["4", "5", "6", "7"], answer: 2, difficulty: 1, fact: "The first letters of each location spell THANOS." },
    { q: "What planet is Thanos from?", options: ["Xandar", "Knowhere", "Titan", "Sakaar"], answer: 2, difficulty: 2, fact: "Titan is a real moon of Saturn." },
    { q: "Which Avenger snaps the Gauntlet in Endgame?", options: ["Thor", "Captain America", "Iron Man", "Hulk"], answer: 2, difficulty: 1, fact: "'I am Iron Man' mirrors his exact words from the first film." },
    { q: "What item does Fury give Carol Danvers?", options: ["Tesseract", "Modified pager", "Shield", "Badge"], answer: 1, difficulty: 3, fact: "That pager's range extends across galaxies." },
    { q: "What protocol destroys Tony's suits in Iron Man 3?", options: ["House Party", "Clean Slate", "Endgame", "Last Resort"], answer: 1, difficulty: 3, fact: "Tony built 35+ suits compulsively as PTSD coping." },
    { q: "In which film is 'Avengers Assemble' first said?", options: ["Avengers 2012", "Age of Ultron", "Infinity War", "Endgame"], answer: 3, difficulty: 2, fact: "Fans waited 22 films to hear Cap say it." },
    { q: "What is Peter Parker's AI suit assistant?", options: ["Friday", "Karen", "Jarvis", "Edith"], answer: 1, difficulty: 2, fact: "Tom Holland named the AI." },
    { q: "Who is the first Avenger in the MCU?", options: ["Iron Man", "Captain America", "Thor", "Hulk"], answer: 0, difficulty: 1, fact: "Iron Man (2008) launched the MCU." },
    { q: "What metal coats Wolverine's skeleton?", options: ["Vibranium", "Adamantium", "Uru", "Carbonadium"], answer: 1, difficulty: 1, fact: "Adamantium is virtually indestructible." },
    { q: "Which planet do the Guardians first meet on?", options: ["Xandar", "Knowhere", "Ego", "Morag"], answer: 3, difficulty: 3, fact: "Quill dancing alone on Morag was Chris Pratt's audition scene." },
    { q: "How many MCU films before Endgame?", options: ["18", "20", "21", "23"], answer: 2, difficulty: 3, fact: "Endgame became highest-grossing at $2.8 billion." },
    { q: "Who is Peter Quill's Celestial father?", options: ["Arishem", "Ego", "Eson", "Tiamut"], answer: 1, difficulty: 2, fact: "Ego is literally a living planet played by Kurt Russell." },
    { q: "What fake name does Natasha use in Iron Man 2?", options: ["Nancy Rushman", "Natalie Rushman", "Nina Rostova", "Nadia Romanoff"], answer: 1, difficulty: 4, fact: "Scarlett Johansson's first MCU appearance was undercover at Stark Industries." },
    { q: "Who nudges Mjolnir in Age of Ultron?", options: ["Black Widow", "Captain America", "Vision", "Hawkeye"], answer: 1, difficulty: 4, fact: "The Russos confirmed Cap was always worthy — he chose not to lift it to spare Thor." },
  ],
  "Cricket": [
    { q: "Who holds the record for most Test runs?", options: ["Ponting", "Kallis", "Sachin Tendulkar", "Brian Lara"], answer: 2, difficulty: 1, fact: "Sachin scored 15,921 Test runs over 24 years." },
    { q: "How many players on a cricket team?", options: ["9", "10", "11", "12"], answer: 2, difficulty: 1, fact: "The 11-player format dates to the 1700s." },
    { q: "Which country won the first World Cup (1975)?", options: ["Australia", "England", "West Indies", "India"], answer: 2, difficulty: 2, fact: "Clive Lloyd's West Indies beat Australia by 17 runs at Lord's." },
    { q: "Who is the 'God of Cricket'?", options: ["Virat Kohli", "MS Dhoni", "Sachin Tendulkar", "Kapil Dev"], answer: 2, difficulty: 1, fact: "When Sachin batted, traffic in Mumbai visibly dropped." },
    { q: "Which IPL team has the most titles?", options: ["CSK", "MI", "KKR", "RCB"], answer: 1, difficulty: 2, fact: "MI has 5 titles — famous for the odd-year winning pattern." },
    { q: "Who hit six 6s in a T20 WC over?", options: ["Chris Gayle", "Yuvraj Singh", "AB de Villiers", "Rohit Sharma"], answer: 1, difficulty: 2, fact: "Yuvraj hit Stuart Broad for 6 sixes. His 50 came in 12 balls." },
    { q: "What is the highest ODI individual score?", options: ["264 Rohit", "219 Sehwag", "200 Sachin", "237 Guptill"], answer: 0, difficulty: 3, fact: "Rohit was dropped on 4 runs — one of cricket's most costly missed catches." },
    { q: "Who took a hat-trick in the first over of a Test?", options: ["Irfan Pathan", "Wasim Akram", "Malinga", "No one"], answer: 0, difficulty: 3, fact: "Irfan got Butt, Younis Khan, and Yousuf at Karachi, 2006." },
    { q: "What was the 'Ball of the Century'?", options: ["Wasim to Atherton", "Warne's first Ashes ball", "Bumrah's yorker", "McGrath at Lord's"], answer: 1, difficulty: 3, fact: "Warne's ball drifted outside leg, spun to clip off stump. Benaud: 'Gatting has absolutely no answer.'" },
    { q: "What does LBW stand for?", options: ["Left Before Wicket", "Leg Before Wicket", "Long Ball Wide", "Leg By Wicket"], answer: 1, difficulty: 1, fact: "LBW is cricket's most debated rule. DRS has helped but hasn't ended debates." },
    { q: "Who captained India to the 1983 World Cup?", options: ["Gavaskar", "Kapil Dev", "Amarnath", "Shastri"], answer: 1, difficulty: 2, fact: "India were 50-1 underdogs. Kapil's 175* wasn't televised — no footage exists." },
    { q: "What is a 'googly'?", options: ["Fast bouncer", "Leg-spin turning the other way", "Slow full toss", "Wide delivery"], answer: 1, difficulty: 2, fact: "Invented by Bosanquet in 1900. The name's origin is unknown." },
    { q: "Which ground is the 'Home of Cricket'?", options: ["The Oval", "Lord's", "Eden Gardens", "MCG"], answer: 1, difficulty: 2, fact: "Lord's was founded in 1814. The ground has a famous 2.5-meter slope." },
    { q: "Who has the most Test wickets?", options: ["Shane Warne", "Muralitharan", "Anil Kumble", "James Anderson"], answer: 1, difficulty: 2, fact: "Murali took 800 Test wickets with his unique bowling action." },
    { q: "What is Duckworth-Lewis used for?", options: ["Rankings", "Rain-affected matches", "Pitch ratings", "Fielding"], answer: 1, difficulty: 2, fact: "Created by two statisticians who met in a pub." },
    { q: "Who scored the fastest ODI century?", options: ["Shahid Afridi", "AB de Villiers", "Corey Anderson", "Chris Gayle"], answer: 1, difficulty: 3, fact: "AB smashed 100 off 31 balls vs West Indies in 2015." },
    { q: "What is MS Dhoni's famous shot?", options: ["Cover drive", "Helicopter shot", "Reverse sweep", "Switch hit"], answer: 1, difficulty: 1, fact: "Dhoni learned it from his friend Santosh Lal in Ranchi." },
    { q: "What was India's lowest Test score ever?", options: ["36", "42", "58", "67"], answer: 0, difficulty: 4, fact: "36 all out vs Australia at Adelaide 2020. India then won the series 2-1." },
    { q: "Who is the only player with 100 international centuries?", options: ["Brian Lara", "Ponting", "Sachin", "Virat Kohli"], answer: 2, difficulty: 2, fact: "It took Sachin over a year to go from 99 to 100 centuries." },
  ],
  "Game of Thrones": [
    { q: "What is House Stark's motto?", options: ["Fire and Blood", "Ours is the Fury", "Winter is Coming", "Hear Me Roar"], answer: 2, difficulty: 1, fact: "Unlike boastful house mottos, the Starks' is a warning." },
    { q: "Who sits on the Iron Throne at the end?", options: ["Jon Snow", "Bran Stark", "Sansa Stark", "No one"], answer: 1, difficulty: 1, fact: "George R.R. Martin called Bran's arc 'the core' of the story." },
    { q: "What is Daenerys's largest dragon?", options: ["Rhaegal", "Viserion", "Drogon", "Balerion"], answer: 2, difficulty: 1, fact: "Drogon's roar was made from lions, tigers, and jet engines." },
    { q: "Who kills the Night King?", options: ["Jon Snow", "Daenerys", "Arya Stark", "Bran Stark"], answer: 2, difficulty: 1, fact: "Maisie Williams' double practiced the dagger move hundreds of times." },
    { q: "What is the Wall made of?", options: ["Stone", "Iron", "Ice", "Dragonglass"], answer: 2, difficulty: 1, fact: "The Wall is 700 feet tall — like a 60-story building of ice." },
    { q: "Who is Jon Snow's real mother?", options: ["Cersei", "Lyanna Stark", "Catelyn", "Melisandre"], answer: 1, difficulty: 2, fact: "R+L=J was predicted by fans in 1997." },
    { q: "What is Arya's direwolf named?", options: ["Lady", "Grey Wind", "Nymeria", "Ghost"], answer: 2, difficulty: 2, fact: "In the books, Arya wargs into Nymeria in dreams, leading a wolf pack." },
    { q: "How many total episodes?", options: ["67", "73", "80", "86"], answer: 1, difficulty: 3, fact: "Each final-season episode cost roughly $15 million." },
    { q: "What poison kills Joffrey?", options: ["Tears of Lys", "Wolfsbane", "The Strangler", "Basilisk Blood"], answer: 2, difficulty: 3, fact: "Hidden in Sansa's necklace by Olenna. Rewatch — you'll see her touch it." },
    { q: "Who is Daenerys's first husband?", options: ["Drogo", "Daario", "Hizdahr", "Jorah"], answer: 0, difficulty: 1, fact: "Jason Momoa got the role by performing a Haka at his audition." },
    { q: "What is wildfire?", options: ["Dragon breath", "Explosive green substance", "A wine", "Forest fire"], answer: 1, difficulty: 2, fact: "Medieval napalm. Cersei used it to destroy the Great Sept." },
    { q: "Who teaches Arya to fight?", options: ["The Hound", "Syrio Forel", "Jaqen H'ghar", "All of them"], answer: 3, difficulty: 2, fact: "Each gave a different skill: Syrio (swordplay), Hound (brutality), Jaqen (assassination)." },
    { q: "What is 'Valar Morghulis'?", options: ["All men must die", "Winter is here", "The night is dark", "Fire and blood"], answer: 0, difficulty: 2, fact: "Response: 'Valar Dohaeris' — All men must serve." },
    { q: "Who pushes Bran from the tower?", options: ["Cersei", "Jaime", "The Mountain", "Littlefinger"], answer: 1, difficulty: 1, fact: "'The things I do for love' — one of the show's most iconic lines." },
    { q: "How did the Mad King die?", options: ["Poisoned", "Stabbed by Jaime", "Burned alive", "Beheaded"], answer: 1, difficulty: 2, fact: "Jaime killed Aerys to stop him burning King's Landing — heroism mistaken for treachery." },
    { q: "Which character says 'Chaos is a ladder'?", options: ["Varys", "Cersei", "Littlefinger", "Tyrion"], answer: 2, difficulty: 2, fact: "Bran later repeats it to Littlefinger to reveal he knows everything." },
    { q: "What is the Night's Watch oath's first line?", options: ["Night gathers", "I am the sword", "Winter is here", "I pledge my life"], answer: 0, difficulty: 4, fact: "Kit Harington nailed the oath recitation at his audition — first try." },
    { q: "Whose sword is 'Heartsbane'?", options: ["Jaime's", "Jorah's", "Sam Tarly's family", "Brienne's"], answer: 2, difficulty: 3, fact: "Sam steals it from Randyll, who threatened to kill him." },
  ],
  "Sacred Games": [
    { q: "Who plays Ganesh Gaitonde?", options: ["Saif Ali Khan", "Nawazuddin Siddiqui", "Pankaj Tripathi", "Ranveer Singh"], answer: 1, difficulty: 1, fact: "Nawazuddin studied Mumbai's underworld dons for weeks." },
    { q: "Which city is Sacred Games set in?", options: ["Delhi", "Kolkata", "Mumbai", "Chennai"], answer: 2, difficulty: 1, fact: "One of Netflix India's first originals." },
    { q: "What phrase does Gaitonde use?", options: ["Mumbai never sleeps", "Apun hi bhagwan hai", "Mumbai is mine", "Game is sacred"], answer: 1, difficulty: 1, fact: "Became one of India's most quoted web series dialogues." },
    { q: "How many days to save Mumbai?", options: ["15", "20", "25", "30"], answer: 2, difficulty: 2, fact: "The 25-day countdown creates the ticking-clock structure." },
    { q: "Who directed Season 1?", options: ["Kashyap only", "Motwane only", "Both", "Zoya Akhtar"], answer: 2, difficulty: 2, fact: "Kashyap directed Gaitonde's past, Motwane handled Sartaj's present." },
    { q: "What is Bunty to Gaitonde?", options: ["Brother", "Right-hand man", "Father", "Rival"], answer: 1, difficulty: 2, fact: "Jatin Sarna's Bunty became a huge fan favorite." },
    { q: "Which platform hosts it?", options: ["Amazon", "Hotstar", "Netflix", "Zee5"], answer: 2, difficulty: 1, fact: "Sacred Games put Indian streaming on the global map." },
    { q: "Who is the RAW agent in Season 2?", options: ["Batya Abelman", "Jojo", "Kusum Devi", "Isa"], answer: 0, difficulty: 3, fact: "Kalki Koechlin connected Gaitonde's story to international espionage." },
    { q: "What novel is it based on?", options: ["Sacred Games by Vikram Chandra", "Bombay by Suketu Mehta", "Shantaram", "Maximum City"], answer: 0, difficulty: 3, fact: "The 900-page novel took 7 years to write." },
    { q: "What real event does the plot parallel?", options: ["1993 Bombay bombings", "1998 nuclear tests", "2008 Mumbai attacks", "Kargil War"], answer: 0, difficulty: 4, fact: "Gaitonde's arc parallels the organized crime behind the 1993 serial bombings." },
    { q: "What is Sartaj's rank?", options: ["Commissioner", "Inspector", "Constable", "ACP"], answer: 1, difficulty: 1, fact: "Saif Ali Khan grew a beard and lost weight for the role." },
    { q: "Who plays Kukoo?", options: ["Kubbra Sait", "Radhika Apte", "Surveen Chawla", "Elnaaz Norouzi"], answer: 0, difficulty: 2, fact: "A breakout moment for transgender representation in Indian content." },
    { q: "What is Trivedi's role?", options: ["Politician", "Guru/Spiritual leader", "Police chief", "Arms dealer"], answer: 1, difficulty: 2, fact: "Pankaj Tripathi's Guruji — a spiritual leader with apocalyptic plans." },
    { q: "What does Gaitonde narrate from?", options: ["Prison", "A bunker", "The afterlife", "Exile"], answer: 2, difficulty: 3, fact: "Dead from episode 1. Narration from beyond death creates the show's structure." },
  ],
  "Friends": [
    { q: "What is Ross's first wife's name?", options: ["Emily", "Carol", "Rachel", "Julie"], answer: 1, difficulty: 1, fact: "Carol left Ross for Susan. His eventual three divorces became a running joke." },
    { q: "What is Joey's catchphrase?", options: ["Could I BE...", "How you doin'?", "We were on a break!", "Oh. My. God."], answer: 1, difficulty: 1, fact: "Matt LeBlanc ad-libbed it — writers made it his signature line." },
    { q: "Where do they hang out?", options: ["Central Park", "Central Perk", "The Apartment", "Joe's Bar"], answer: 1, difficulty: 1, fact: "The orange couch was found in the Warner Bros. studio basement." },
    { q: "How many seasons?", options: ["8", "9", "10", "12"], answer: 2, difficulty: 1, fact: "236 episodes. The cast each earned $1M per episode in the final season." },
    { q: "What is Monica's profession?", options: ["Fashion buyer", "Chef", "Waitress", "Paleontologist"], answer: 1, difficulty: 2, fact: "Courteney Cox learned professional knife techniques for the role." },
    { q: "What is Phoebe's twin's name?", options: ["Ursula", "Regina", "Frances", "Lily"], answer: 0, difficulty: 3, fact: "Ursula was originally Lisa Kudrow's character on 'Mad About You.'" },
    { q: "Who said 'We were on a break!'?", options: ["Joey", "Chandler", "Ross", "Rachel"], answer: 2, difficulty: 1, fact: "Appears 85 times. The writers never settled whether it was true." },
    { q: "What is Ross's monkey named?", options: ["George", "Marcel", "Clyde", "Darwin"], answer: 1, difficulty: 2, fact: "Schwimmer reportedly did not enjoy working with the monkey." },
    { q: "What is Joey's stuffed penguin called?", options: ["Waddles", "Hugsy", "Flipper", "Tux"], answer: 1, difficulty: 2, fact: "Hugsy is a bestselling Friends merch item." },
    { q: "What song does Phoebe sing?", options: ["Rainy Day", "Smelly Cat", "Fuzzy Duck", "Morning Sun"], answer: 1, difficulty: 1, fact: "Lisa Kudrow played guitar. The song was written to be deliberately terrible." },
    { q: "What is Chandler's job?", options: ["IT Procurement", "Statistical Analysis", "Transponster", "Data Config"], answer: 1, difficulty: 3, fact: "Nobody could remember. Rachel guesses 'transponster' — 'THAT'S NOT EVEN A WORD!'" },
    { q: "Who does Monica marry?", options: ["Richard", "Chandler", "Pete", "Fun Bobby"], answer: 1, difficulty: 1, fact: "Audience reaction to their London hookup was so strong, writers made it permanent." },
    { q: "What does Rachel get off the plane for?", options: ["Passport", "Ross", "Luggage", "Phone call"], answer: 1, difficulty: 1, fact: "The live audience reaction was genuine." },
    { q: "What is Chandler's middle name?", options: ["Michael", "Muriel", "Martin", "Mitchell"], answer: 1, difficulty: 2, fact: "Chandler Muriel Bing." },
    { q: "Which vestibule episode is Chandler in?", options: ["The Blackout", "Power Outage", "Ross Finds Out", "Pilot"], answer: 0, difficulty: 4, fact: "This aired during a multi-show NYC blackout storyline across NBC." },
  ],
  "Indian Independence": [
    { q: "When did India gain independence?", options: ["1945", "1946", "1947", "1948"], answer: 2, difficulty: 1, fact: "At midnight, Nehru delivered the 'Tryst with Destiny' speech." },
    { q: "Who was India's first PM?", options: ["Gandhi", "Patel", "Nehru", "Ambedkar"], answer: 2, difficulty: 1, fact: "Nehru served 17 years — the longest-serving Indian PM." },
    { q: "What was the Salt March called?", options: ["Quit India March", "Dandi March", "Swadeshi March", "Satyagraha March"], answer: 1, difficulty: 2, fact: "Gandhi walked 240 miles in 24 days. Picking up salt broke British law." },
    { q: "Which 1942 movement did Gandhi launch?", options: ["Non-Cooperation", "Civil Disobedience", "Quit India", "Swadeshi"], answer: 2, difficulty: 2, fact: "Within hours of 'Do or Die,' the entire Congress leadership was arrested." },
    { q: "Who founded the Indian National Congress?", options: ["A.O. Hume", "Dadabhai Naoroji", "Gokhale", "Tilak"], answer: 0, difficulty: 3, fact: "A British civil servant founded the org that would end British rule." },
    { q: "When was the Jallianwala Bagh massacre?", options: ["1917", "1919", "1921", "1923"], answer: 1, difficulty: 2, fact: "General Dyer ordered fire on a peaceful Baisakhi gathering. Walls still bear bullet holes." },
    { q: "Who is 'Netaji'?", options: ["Bhagat Singh", "Subhas Chandra Bose", "Lala Lajpat Rai", "Azad"], answer: 1, difficulty: 1, fact: "'Give me blood, and I shall give you freedom' electrified a generation." },
    { q: "Who drafted the Constitution?", options: ["Nehru", "Gandhi", "Ambedkar", "Rajendra Prasad"], answer: 2, difficulty: 1, fact: "Born Dalit, Ambedkar became one of India's most educated citizens." },
    { q: "How old was Bhagat Singh at execution?", options: ["21", "23", "25", "27"], answer: 1, difficulty: 3, fact: "Executed at 23, he walked to the gallows singing 'Rang de Basanti.'" },
    { q: "Who was the last Viceroy?", options: ["Mountbatten", "Irwin", "Wavell", "Curzon"], answer: 0, difficulty: 3, fact: "The Radcliffe Line displaced over 15 million people." },
    { q: "Who gave the slogan 'Jai Hind'?", options: ["Gandhi", "Nehru", "Bose", "Patel"], answer: 2, difficulty: 2, fact: "Bose coined it as the greeting of the Indian National Army." },
    { q: "Who is the 'Iron Man of India'?", options: ["Nehru", "Bhagat Singh", "Sardar Patel", "Bose"], answer: 2, difficulty: 1, fact: "Patel integrated 562 princely states. The Statue of Unity is 182m tall." },
    { q: "Who wrote 'Vande Mataram'?", options: ["Tagore", "Bankim Chandra", "Iqbal", "Premchand"], answer: 1, difficulty: 2, fact: "Written in 1875, first sung at an INC session in 1896." },
    { q: "What was the first INC session?", options: ["Bombay 1885", "Calcutta 1886", "Madras 1887", "Delhi 1888"], answer: 0, difficulty: 4, fact: "72 delegates attended. Today's Congress descends from this meeting." },
  ],
  "Football / Soccer": [
    { q: "Most FIFA World Cup wins?", options: ["Germany", "Argentina", "Italy", "Brazil"], answer: 3, difficulty: 1, fact: "Brazil has 5 titles and played every World Cup since 1930." },
    { q: "Players per team on field?", options: ["9", "10", "11", "12"], answer: 2, difficulty: 1, fact: "11-a-side standardized in 1897 by the English FA." },
    { q: "Most Ballon d'Or awards?", options: ["Ronaldo", "Messi", "Pelé", "Zidane"], answer: 1, difficulty: 1, fact: "Messi has 8. First came in 2009 at age 22." },
    { q: "Which club is 'The Red Devils'?", options: ["Liverpool", "Arsenal", "Manchester United", "Bayern"], answer: 2, difficulty: 2, fact: "Named by a French journalist in 1934 during a tour." },
    { q: "2022 World Cup host?", options: ["Russia", "Qatar", "Brazil", "Japan"], answer: 1, difficulty: 1, fact: "First winter World Cup. Argentina's win was a legendary final." },
    { q: "Most Champions League titles?", options: ["Barcelona", "AC Milan", "Real Madrid", "Liverpool"], answer: 2, difficulty: 2, fact: "15 titles. They won the first 5 in a row (1956-60)." },
    { q: "What is the 'Hand of God'?", options: ["Pelé's kick", "Maradona's handball", "Zidane's headbutt", "Messi's run"], answer: 1, difficulty: 2, fact: "Maradona credited 'the hand of God and the head of Maradona.'" },
    { q: "Fastest PL hat-trick?", options: ["Sadio Mané", "Robbie Fowler", "Haaland", "Agüero"], answer: 0, difficulty: 3, fact: "3 goals in 2 min 56 sec for Southampton in 2015." },
    { q: "Goalkeeper with most career goals?", options: ["Higuita", "Rogério Ceni", "Neuer", "Campos"], answer: 1, difficulty: 4, fact: "131 goals — more than many strikers. Free kick specialist over 25 years." },
    { q: "Standard match length?", options: ["80 min", "90 min", "100 min", "120 min"], answer: 1, difficulty: 1, fact: "The longest pro match lasted 35 hours — a charity event." },
    { q: "What does a red card mean?", options: ["Warning", "Penalty", "Sending off", "Free kick"], answer: 2, difficulty: 1, fact: "Cards were invented for the 1970 World Cup after language barriers caused confusion." },
    { q: "YNWA anthem belongs to?", options: ["Man United", "Chelsea", "Liverpool", "Tottenham"], answer: 2, difficulty: 2, fact: "Originally from a 1945 musical. Liverpool fans adopted it in the 1960s." },
    { q: "What is the 'Cruyff Turn'?", options: ["Stadium", "Signature move", "Training drill", "Formation"], answer: 1, difficulty: 2, fact: "Cruyff invented it during the 1974 World Cup vs Sweden." },
    { q: "First World Cup winner (1930)?", options: ["Brazil", "Argentina", "Uruguay", "Italy"], answer: 2, difficulty: 2, fact: "Uruguay hosted and won. Only 13 teams participated." },
  ],
  "Scam 1992": [
    { q: "Who plays Harshad Mehta?", options: ["Nawazuddin", "Pratik Gandhi", "Rajkummar Rao", "Manoj Bajpayee"], answer: 1, difficulty: 1, fact: "Pratik binge-watched real Harshad Mehta interviews." },
    { q: "Which journalist exposed the scam?", options: ["Barkha Dutt", "Sucheta Dalal", "Rajdeep", "Arnab"], answer: 1, difficulty: 1, fact: "Sucheta's Times of India exposé on April 23, 1992 triggered everything." },
    { q: "Central stock exchange?", options: ["NSE", "BSE", "NYSE", "LSE"], answer: 1, difficulty: 2, fact: "BSE (est. 1875) is Asia's oldest. The scam gave SEBI statutory powers." },
    { q: "What did Mehta manipulate?", options: ["Derivatives", "Bank Receipts", "Bonds", "Futures"], answer: 1, difficulty: 2, fact: "Fake BRs siphoned money from banks to stocks with zero oversight." },
    { q: "Mehta's nickname?", options: ["Big Bull", "Stock King", "Market Maker", "Money Man"], answer: 0, difficulty: 1, fact: "He moved Sensex from 1,000 to 4,500 and drove India's first Lexus." },
    { q: "Who directed it?", options: ["Anurag Kashyap", "Hansal Mehta", "Motwane", "Imtiaz Ali"], answer: 1, difficulty: 2, fact: "Hansal Mehta (no relation) spent years researching the scam." },
    { q: "What happened to Harshad?", options: ["Escaped", "Acquitted", "Died in custody", "Became minister"], answer: 2, difficulty: 2, fact: "Heart attack in Thane jail, 2001, aged 47, with 27 pending cases." },
    { q: "The show's iconic theme?", options: ["Kal Ho Naa Ho", "Achint's theme", "Chaiyya Chaiyya", "Kun Faya Kun"], answer: 1, difficulty: 2, fact: "Used in thousands of motivational and trading memes." },
    { q: "Amount Mehta accused of siphoning?", options: ["₹500Cr", "₹1,000Cr", "₹3,500Cr", "₹5,000Cr"], answer: 3, difficulty: 3, fact: "₹5,000 crore in 1992 — tens of thousands of crores today." },
    { q: "Mehta's claim about the PM?", options: ["Paid ₹1Cr to PM Rao", "Had dinner with PM", "Funded party", "Bribed FM"], answer: 0, difficulty: 4, fact: "Claimed on live TV. Never proven or disproven." },
    { q: "Who plays Sucheta Dalal?", options: ["Shreya Dhanwanthary", "Radhika Apte", "Rani Mukerji", "Konkona Sen"], answer: 0, difficulty: 2, fact: "Shreya spent time with the real Sucheta to understand her determination." },
    { q: "Which car did Mehta famously own?", options: ["BMW 7", "Lexus LS400", "Mercedes S-Class", "Toyota Cressida"], answer: 1, difficulty: 2, fact: "India's first Lexus. License plate reportedly read 'BSE.'" },
  ],
  "World Capitals": [
    { q: "Capital of Japan?", options: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], answer: 2, difficulty: 1, fact: "'Tokyo' literally means 'Eastern Capital.'" },
    { q: "Capital of Brazil?", options: ["São Paulo", "Rio", "Brasília", "Salvador"], answer: 2, difficulty: 2, fact: "Built from scratch in 41 months. Shaped like an airplane from the air." },
    { q: "Capital of Turkey?", options: ["Istanbul", "Ankara", "Izmir", "Antalya"], answer: 1, difficulty: 2, fact: "Atatürk moved it from Istanbul in 1923 to break from the Ottoman past." },
    { q: "Capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], answer: 3, difficulty: 2, fact: "Queen Victoria chose Ottawa partly because it was far from the US border." },
    { q: "Capital of Egypt?", options: ["Alexandria", "Cairo", "Luxor", "Giza"], answer: 1, difficulty: 1, fact: "Africa's largest city. Arabic name 'Al-Qāhirah' means 'The Victorious.'" },
    { q: "Capital of Switzerland?", options: ["Geneva", "Zurich", "Bern", "Basel"], answer: 2, difficulty: 3, fact: "Technically the 'federal city' — Switzerland has no official capital." },
    { q: "Capital of New Zealand?", options: ["Auckland", "Christchurch", "Wellington", "Queenstown"], answer: 2, difficulty: 2, fact: "World's southernmost capital of a sovereign state." },
    { q: "Capital of Myanmar?", options: ["Yangon", "Mandalay", "Naypyidaw", "Bagan"], answer: 2, difficulty: 3, fact: "Built in secret. 20-lane highways eerily empty." },
    { q: "Capital of Vietnam?", options: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"], answer: 1, difficulty: 2, fact: "Hanoi means 'between rivers.' Many assume it's Ho Chi Minh City." },
    { q: "Capital of South Africa (legislative)?", options: ["Johannesburg", "Cape Town", "Pretoria", "Durban"], answer: 1, difficulty: 4, fact: "South Africa has THREE capitals: Pretoria, Cape Town, Bloemfontein." },
    { q: "Capital of Morocco?", options: ["Casablanca", "Marrakech", "Rabat", "Fez"], answer: 2, difficulty: 3, fact: "Most guess Casablanca. Rabat has been capital since 1912." },
    { q: "Capital of Kazakhstan?", options: ["Almaty", "Astana", "Shymkent", "Karaganda"], answer: 1, difficulty: 3, fact: "Renamed Nur-Sultan in 2019, then back to Astana in 2022." },
  ],
  "The Family Man": [
    { q: "Who plays Srikant?", options: ["Pankaj Tripathi", "Manoj Bajpayee", "Nawazuddin", "Kay Kay Menon"], answer: 1, difficulty: 1, fact: "Bajpayee almost turned it down. Changed his mind after episode 1's script." },
    { q: "Srikant works for?", options: ["RAW", "IB", "TASC", "NIA"], answer: 2, difficulty: 2, fact: "TASC is fictional but inspired by real counter-terrorism units." },
    { q: "Season 2 is set in?", options: ["Mumbai", "Delhi", "Chennai", "Kolkata"], answer: 2, difficulty: 2, fact: "Explored Tamil resistance politics with nuance." },
    { q: "Who plays Raji?", options: ["Priyamani", "Samantha", "Nayanthara", "Rashmika"], answer: 1, difficulty: 1, fact: "Samantha's digital debut. She trained in combat for the role." },
    { q: "Which platform?", options: ["Netflix", "Hotstar", "Amazon Prime", "Zee5"], answer: 2, difficulty: 1, fact: "Amazon paid ₹100+ crore." },
    { q: "Who created it?", options: ["Anurag Kashyap", "Raj & DK", "Vikram Bhatt", "Hansal Mehta"], answer: 1, difficulty: 2, fact: "They made Srikant ordinary — no six-pack, just a tired dad." },
    { q: "Season 1's major threat?", options: ["Cyber attack", "Chemical attack", "Nuclear threat", "Assassination"], answer: 1, difficulty: 2, fact: "Inspired by real-world threats researched for months." },
    { q: "Srikant's daughter?", options: ["Dhriti", "Pihu", "Myra", "Riya"], answer: 0, difficulty: 3, fact: "Dhriti's rebellion mirrors real intelligence officers' families." },
    { q: "Arvind's annoying topic?", options: ["Real estate", "Crypto", "Mutual funds", "Stocks"], answer: 2, difficulty: 2, fact: "'Mutual funds sahi hai' became a massive meme." },
    { q: "What is Chellam Sir?", options: ["Villain", "Retired agent who knows everything", "Tech expert", "Double agent"], answer: 1, difficulty: 2, fact: "Chellam Sir became the 'Indian Google' meme — he knows everything." },
    { q: "Who says 'minimum guy'?", options: ["JK", "Srikant", "Milind", "Arvind"], answer: 0, difficulty: 3, fact: "Sharib Hashmi's JK steals every scene as the self-deprecating sidekick." },
    { q: "Srikant's cover job?", options: ["Software at NII", "Analyst at NCMC", "Clerk at PMO", "Consultant"], answer: 1, difficulty: 4, fact: "Comedy of saving the nation while fixing family drama is the show's weapon." },
  ],
  "Disney Movies": [
    { q: "Simba's father?", options: ["Scar", "Mufasa", "Rafiki", "Zazu"], answer: 1, difficulty: 1, fact: "James Earl Jones voiced Mufasa. The stampede took 3 years to animate." },
    { q: "Which princess has ice powers?", options: ["Rapunzel", "Moana", "Elsa", "Ariel"], answer: 2, difficulty: 1, fact: "Elsa was originally a villain. 'Let It Go' changed the entire plot." },
    { q: "What does Hakuna Matata mean?", options: ["Be brave", "No worries", "Stay strong", "Live free"], answer: 1, difficulty: 1, fact: "Real Swahili phrase. Tourism to Kenya spiked after The Lion King." },
    { q: "Which film has a magic carpet?", options: ["Tangled", "Moana", "Aladdin", "Brave"], answer: 2, difficulty: 1, fact: "The carpet was animated with puppy-like personality despite having no face." },
    { q: "Little Mermaid villain?", options: ["Maleficent", "Ursula", "Cruella", "Gaston"], answer: 1, difficulty: 1, fact: "Ursula was inspired by drag queen Divine." },
    { q: "What fish is Nemo?", options: ["Goldfish", "Blue tang", "Clownfish", "Angelfish"], answer: 2, difficulty: 1, fact: "Demand for pet clownfish surged 40% after the film." },
    { q: "First Pixar feature film?", options: ["A Bug's Life", "Toy Story", "Monsters Inc", "Nemo"], answer: 1, difficulty: 2, fact: "First fully computer-animated feature (1995). 800,000 machine hours." },
    { q: "How many balloons in Up?", options: ["1,000", "10,000", "20,622", "100,000"], answer: 2, difficulty: 3, fact: "Pixar calculated exactly. In reality, ~12 million helium balloons needed." },
    { q: "Which princess is based on a real person?", options: ["Mulan", "Pocahontas", "Moana", "Rapunzel"], answer: 1, difficulty: 2, fact: "Her true story is far more complex and tragic than Disney's version." },
    { q: "Voice of Woody?", options: ["Tim Allen", "Tom Hanks", "Billy Crystal", "Robin Williams"], answer: 1, difficulty: 1, fact: "'There's a snake in my boot!' was ad-libbed." },
    { q: "What does WALL-E stand for?", options: ["Waste Allocation Load Lifter: Earth-class", "World Auto Land Leveler", "Wired Loader", "Nothing"], answer: 0, difficulty: 3, fact: "First 40 minutes have almost no speech. Only 700 words total." },
    { q: "Which villain has the most screen time?", options: ["Scar", "Maleficent", "Jafar", "Captain Hook"], answer: 0, difficulty: 4, fact: "~17 minutes. Jeremy Irons' voice gave out during 'Be Prepared.'" },
    { q: "Which film features 'A Whole New World'?", options: ["Cinderella", "Aladdin", "Beauty and the Beast", "Tangled"], answer: 1, difficulty: 1, fact: "Only Disney song to reach #1 on Billboard Hot 100." },
  ],
  "Harry Potter": [
    { q: "Harry's Hogwarts house?", options: ["Slytherin", "Ravenclaw", "Gryffindor", "Hufflepuff"], answer: 2, difficulty: 1, fact: "The Hat considered Slytherin. Harry's choice proved choices define us." },
    { q: "What does Expecto Patronum produce?", options: ["Shield", "Patronus", "Fire", "Light"], answer: 1, difficulty: 1, fact: "Harry's stag Patronus represents his father James." },
    { q: "How many Horcruxes?", options: ["5", "6", "7", "8"], answer: 2, difficulty: 2, fact: "7 intended. Harry was an accidental 8th." },
    { q: "Harry's Quidditch position?", options: ["Chaser", "Beater", "Keeper", "Seeker"], answer: 3, difficulty: 1, fact: "Youngest Seeker in a century. Got the spot after one catch." },
    { q: "What is the Deathly Hallows symbol?", options: ["Triangle, circle, line", "Star, moon, wand", "Snake, skull, mark", "Lightning, wand, stone"], answer: 0, difficulty: 2, fact: "Triangle=Cloak, circle=Stone, line=Wand. Rowling designed it." },
    { q: "Who kills Dumbledore?", options: ["Voldemort", "Snape", "Draco", "Bellatrix"], answer: 1, difficulty: 1, fact: "At Dumbledore's own request — the series' biggest twist." },
    { q: "What is Snape's Patronus?", options: ["Stag", "Doe", "Snake", "Raven"], answer: 1, difficulty: 2, fact: "Same as Lily Potter's. 'Always.' Rickman knew from the start." },
    { q: "What does the Mirror of Erised show?", options: ["Future", "Deepest desire", "Fears", "Truth"], answer: 1, difficulty: 2, fact: "'Erised' is 'desire' backwards. Dumbledore said he sees socks." },
    { q: "Hagrid's three-headed dog?", options: ["Fang", "Fluffy", "Norbert", "Buckbeak"], answer: 1, difficulty: 1, fact: "Bought from 'a Greek chappie.' Based on Cerberus." },
    { q: "Who teaches Potions first year?", options: ["Slughorn", "Snape", "McGonagall", "Quirrell"], answer: 1, difficulty: 1, fact: "Snape wanted Defense Against the Dark Arts but was denied for years." },
    { q: "What does Felix Felicis do?", options: ["Invisibility", "Grants luck", "Mind reading", "Healing"], answer: 1, difficulty: 2, fact: "'Liquid luck.' Banned in competitions. Overuse causes overconfidence." },
    { q: "Harry's wand core?", options: ["Dragon heartstring", "Unicorn hair", "Phoenix feather", "Thestral hair"], answer: 2, difficulty: 2, fact: "Same core as Voldemort's — feathers from Dumbledore's phoenix, Fawkes." },
    { q: "What is a Muggle?", options: ["Wizard child", "Non-magical person", "Squib", "House-elf"], answer: 1, difficulty: 1, fact: "'Muggle' was added to the Oxford English Dictionary in 2003." },
    { q: "Voldemort's age at first Horcrux?", options: ["14", "16", "18", "20"], answer: 1, difficulty: 4, fact: "Tom Riddle murdered Moaning Myrtle and split his soul at just 16." },
    { q: "What is Hermione's Patronus?", options: ["Cat", "Otter", "Horse", "Hare"], answer: 1, difficulty: 3, fact: "Rowling's favorite animal. Ron's terrier famously chases otters." },
    { q: "Room of Requirement is on which floor?", options: ["Third", "Fifth", "Seventh", "Moves"], answer: 2, difficulty: 3, fact: "Walk past three times thinking of what you need." },
  ],
  "The Office (US)": [
    { q: "Scranton regional manager?", options: ["Dwight", "Michael Scott", "Jim", "Andy"], answer: 1, difficulty: 1, fact: "Carell was supposed to leave after Season 2." },
    { q: "What does Dunder Mifflin sell?", options: ["Electronics", "Paper", "Insurance", "Software"], answer: 1, difficulty: 1, fact: "A paper company in the digital age — the absurdity is the point." },
    { q: "Dwight's farm?", options: ["Shrute Farms", "Schrute Farms", "Dwight's Beets", "Beet Lodge"], answer: 1, difficulty: 1, fact: "Rainn Wilson grew actual beets to stay in character." },
    { q: "Michael's catchphrase?", options: ["Bears Beets BSG", "That's what she said", "I am the manager", "Dunder Mifflin this is..."], answer: 1, difficulty: 1, fact: "Carell improvised many instances. It appears 35+ times." },
    { q: "Who declares bankruptcy?", options: ["Kevin", "Michael", "Andy", "Creed"], answer: 1, difficulty: 2, fact: "Oscar: 'You can't just say it.' Michael: 'I didn't say it, I declared it.'" },
    { q: "Who is the Scranton Strangler?", options: ["Toby", "Creed", "Gabe", "Never revealed"], answer: 3, difficulty: 2, fact: "Fan theory says Toby. The evidence is surprisingly compelling." },
    { q: "Kevin's famous recipe?", options: ["Brownies", "Chili", "Cookies", "Mac and cheese"], answer: 1, difficulty: 2, fact: "He spills it everywhere. One take, improvised." },
    { q: "Who replaces Michael?", options: ["Dwight immediately", "Andy then others", "Jim", "Robert California"], answer: 1, difficulty: 2, fact: "The show cycled managers after Carell left in Season 7." },
    { q: "What does Michael burn his foot on?", options: ["Hot coals", "George Foreman grill", "Iron", "Campfire"], answer: 1, difficulty: 2, fact: "He grills bacon next to his bed and steps on it." },
    { q: "Michael's nemesis?", options: ["Dwight", "Toby", "Jan", "David Wallace"], answer: 1, difficulty: 1, fact: "'Why are you the way that you are?' Never explained." },
    { q: "In the finale, who becomes manager?", options: ["Jim", "Dwight", "Andy", "Darryl"], answer: 1, difficulty: 2, fact: "Dwight finally gets it. Michael returns for the finale." },
    { q: "Michael's spy movie?", options: ["Threat Level Midnight", "Michael Scott Story", "Agent Scarn", "Dunder Movie"], answer: 0, difficulty: 2, fact: "Features the entire office cast. Took years to make in-universe." },
    { q: "How many seasons?", options: ["7", "8", "9", "10"], answer: 2, difficulty: 2, fact: "9 seasons, 201 episodes. Carell left after 7." },
    { q: "What animal does Dwight bring to office?", options: ["Cat", "Bat", "Raccoon", "Goose"], answer: 1, difficulty: 3, fact: "Jim pretends he's been bitten and is turning into a vampire." },
    { q: "Creed's dark secret?", options: ["Wanted criminal", "Not really Creed", "Runs a cult", "All implied"], answer: 3, difficulty: 3, fact: "His real name IS Creed Bratton. Murder, identity theft — all played for laughs." },
    { q: "What does Prison Mike warn about?", options: ["Dementors", "Food", "Guards", "Escapes"], answer: 0, difficulty: 4, fact: "'The dementors. Like in Harry Potter.' Peak Michael Scott." },
  ],
  "Panchayat": [
    { q: "Who plays Abhishek?", options: ["Jitendra Kumar", "Raghubir Yadav", "Faisal Malik", "Chandan Roy"], answer: 0, difficulty: 1, fact: "Already a TVF star. His frustration as an educated outsider struck a chord." },
    { q: "Abhishek's job?", options: ["Teacher", "Panchayat Secretary", "Doctor", "Police"], answer: 1, difficulty: 1, fact: "Took the government job while preparing for CAT. Millions related." },
    { q: "Name of the village?", options: ["Phulera", "Ballia", "Sitapur", "Mandla"], answer: 0, difficulty: 1, fact: "Fictional but filmed in real Madhya Pradesh villages." },
    { q: "Who plays Pradhan's wife?", options: ["Neena Gupta", "Sunita Rajwar", "Faisal Malik", "No such character"], answer: 0, difficulty: 2, fact: "Manju Devi runs things — reflecting the real 'Pradhan Pati' practice." },
    { q: "Which platform?", options: ["Netflix", "Hotstar", "Amazon Prime", "Zee5"], answer: 2, difficulty: 1, fact: "One of Amazon Prime India's most-watched despite zero big stars." },
    { q: "Who is Prahlad?", options: ["Pradhan", "Up-Pradhan", "Secretary", "Sarpanch"], answer: 1, difficulty: 2, fact: "Faisal Malik's Prahlad mediates between Abhishek and villagers." },
    { q: "Who plays Brij Bhushan?", options: ["Raghubir Yadav", "Pankaj Tripathi", "Chandan Roy", "Durgesh Kumar"], answer: 2, difficulty: 2, fact: "The rival who wants the Pradhan seat. Political intrigue in a sleepy village." },
    { q: "What does Abhishek prepare for?", options: ["UPSC", "CAT exam", "Bank PO", "SSC"], answer: 1, difficulty: 2, fact: "Resonated with millions stuck in jobs while chasing competitive exams." },
    { q: "What animal causes trouble in S1?", options: ["Tiger", "Snake", "Bull", "Monkey"], answer: 0, difficulty: 3, fact: "A tiger scare creates chaos — both panic and bureaucratic absurdity." },
    { q: "Who created Panchayat?", options: ["TVF", "Raj & DK", "Excel", "Clean Slate"], answer: 0, difficulty: 2, fact: "The Viral Fever — known for relatable Indian content." },
    { q: "Which season has a romance subplot?", options: ["Season 1", "Season 2", "Season 3", "No romance"], answer: 1, difficulty: 2, fact: "Abhishek-Rinki develops naturally — no Bollywood drama." },
    { q: "How does the show handle caste?", options: ["Ignores it", "Heavy lectures", "Subtle everyday interactions", "Doesn't exist"], answer: 2, difficulty: 4, fact: "Shows privilege gaps through Abhishek's outsider perspective without preaching." },
  ],
  "Internet Memes": [
    { q: "What animal is Doge?", options: ["Cat", "Shiba Inu", "Corgi", "Pug"], answer: 1, difficulty: 1, fact: "Original photo: Kabosu, a rescue Shiba Inu in Japan." },
    { q: "When did Gangnam Style go viral?", options: ["2010", "2011", "2012", "2013"], answer: 2, difficulty: 1, fact: "First YouTube video to reach 1 billion views." },
    { q: "'This is fine' features who?", options: ["Cat", "Stick figure", "Dog", "Man"], answer: 2, difficulty: 2, fact: "From KC Green's webcomic. Symbol of denial in crisis." },
    { q: "What is Rickrolling?", options: ["Skateboard trick", "Tricking into Rick Astley video", "Cooking technique", "Dance move"], answer: 1, difficulty: 1, fact: "Rick Astley himself finds it hilarious." },
    { q: "What does 'F' in chat mean?", options: ["Fun", "Pay respects", "Fail", "Follow"], answer: 1, difficulty: 1, fact: "From Call of Duty: 'Press F to Pay Respects' at a funeral." },
    { q: "Distracted Boyfriend is about?", options: ["Man looking at another woman", "Breakup", "Social media", "Work cheating"], answer: 0, difficulty: 1, fact: "Stock photo by Antonio Guillem, 2015. Had no idea it'd go viral." },
    { q: "What does GOAT stand for?", options: ["Go Away Today", "Greatest Of All Time", "Get On A Train", "Good At Things"], answer: 1, difficulty: 1, fact: "Muhammad Ali's wife first used it. Internet adopted it for everything." },
    { q: "Who is Bad Luck Brian?", options: ["Fictional", "Real person named Kyle", "Comedian", "AI"], answer: 1, difficulty: 2, fact: "Kyle Craven's yearbook photo. He sold an NFT of it." },
    { q: "'Loss' meme is?", options: ["Financial meme", "Minimalist 4-panel reference", "Gaming term", "Crypto crash"], answer: 1, difficulty: 3, fact: "From CAD webcomic. Reduced to |, ||, ||, |_ — found in everything." },
    { q: "Woman yelling at cat features?", options: ["Random cat", "Smudge the Cat", "Karen's cat", "Angry cat"], answer: 1, difficulty: 2, fact: "Combines Real Housewives scene with Smudge the Cat photo." },
    { q: "What does 'Based' mean online?", options: ["Basic", "Controversial but authentic", "Wrong", "Beautiful"], answer: 1, difficulty: 3, fact: "Popularized by Lil B. Means expressing unpopular opinions confidently." },
    { q: "First major viral video?", options: ["Charlie Bit My Finger", "Numa Numa", "Keyboard Cat", "Evolution of Dance"], answer: 1, difficulty: 3, fact: "Gary Brolsma's lip-sync went viral in 2004 — before YouTube existed." },
    { q: "What is 'Stonks'?", options: ["Misspelling of stocks", "Stones", "Stunts", "Stinks"], answer: 0, difficulty: 1, fact: "Meme Man + stock graph = symbol of questionable financial decisions." },
    { q: "Keyboard Cat's real name?", options: ["Piano", "Keyboard Cat", "Musical Kitty", "Fatso"], answer: 3, difficulty: 4, fact: "Filmed in 1984, uploaded 2007. The cat's actual name was Fatso." },
  ],
  "Famous Logos": [
    { q: "What animal is the Puma logo?", options: ["Lion", "Puma/Cougar", "Cheetah", "Jaguar"], answer: 1, difficulty: 1, fact: "Puma and Adidas were founded by feuding brothers in the same German town." },
    { q: "How many rings in the Audi logo?", options: ["3", "4", "5", "6"], answer: 1, difficulty: 1, fact: "Each ring = one of four companies that merged in 1932." },
    { q: "Which company has the swoosh?", options: ["Adidas", "Nike", "Puma", "Reebok"], answer: 1, difficulty: 1, fact: "Designed for $35 in 1971. Nike later gave the designer stock worth $1M+." },
    { q: "Lamborghini logo animal?", options: ["Horse", "Bull", "Lion", "Eagle"], answer: 1, difficulty: 2, fact: "Ferruccio was a Taurus. Models named after famous fighting bulls." },
    { q: "McDonald's arches shaped like?", options: ["M", "W", "Burger", "French fry"], answer: 0, difficulty: 1, fact: "The arches were actual architecture before becoming the logo." },
    { q: "Which logo has a hidden arrow?", options: ["Amazon", "FedEx", "Dell", "IBM"], answer: 1, difficulty: 2, fact: "Between E and X. Once you see it, you can never unsee it." },
    { q: "What does Amazon's arrow mean?", options: ["Smile + A to Z", "Speed", "Growth", "Connection"], answer: 0, difficulty: 2, fact: "A to Z = sells everything. Also looks like a smile." },
    { q: "What's hidden in Baskin-Robbins?", options: ["Number 31", "Cone", "BR text", "Scoop"], answer: 0, difficulty: 2, fact: "Pink parts of 'BR' form '31' — one flavor per day of the month." },
    { q: "Which car has a prancing horse?", options: ["Porsche", "Ferrari", "Mustang", "Lamborghini"], answer: 1, difficulty: 1, fact: "From WWI pilot Baracca's plane. His mother suggested Enzo use it." },
    { q: "Google logo's color pattern?", options: ["Primary only", "Primary + one secondary", "Random", "RGB"], answer: 1, difficulty: 3, fact: "Blue, red, yellow (primary) then green (secondary) — shows Google breaks rules." },
    { q: "Which logo was designed on a napkin?", options: ["Nike", "Virgin", "Starbucks", "Under Armour"], answer: 0, difficulty: 3, fact: "Phil Knight: 'I don't love it, but it'll grow on me.' Understatement of the century." },
    { q: "Which brand has interlocking C's?", options: ["Cartier", "Chanel", "Coach", "Céline"], answer: 1, difficulty: 2, fact: "Coco Chanel designed it herself in 1925." },
    { q: "What is the Starbucks logo?", options: ["Coffee cup", "Mermaid/siren", "Bean", "Star"], answer: 1, difficulty: 1, fact: "Based on a 16th-century Norse woodcut. Original was much more revealing." },
    { q: "Coca-Cola logo color?", options: ["Blue", "Red", "Green", "Orange"], answer: 1, difficulty: 1, fact: "The red is trademarked. Coke popularized Santa's red suit." },
  ],
  "World Flags": [
    { q: "Maple leaf flag?", options: ["USA", "Canada", "Australia", "NZ"], answer: 1, difficulty: 1, fact: "Only adopted in 1965. Before that, they used a British Red Ensign." },
    { q: "What color is NOT on India's flag?", options: ["Saffron", "White", "Blue", "Green"], answer: 2, difficulty: 1, fact: "Ashoka Chakra is navy blue, but blue isn't one of the three bands." },
    { q: "Dragon on whose flag?", options: ["China", "Japan", "Bhutan", "Mongolia"], answer: 2, difficulty: 2, fact: "Bhutan = 'Druk Yul' — Land of the Thunder Dragon." },
    { q: "Only non-rectangular flag?", options: ["Switzerland", "Nepal", "Vatican", "Bhutan"], answer: 1, difficulty: 2, fact: "Two stacked triangles. Mathematically defined in the constitution." },
    { q: "French flag colors?", options: ["Red White Green", "Blue White Red", "Red Yellow Blue", "White Green Orange"], answer: 1, difficulty: 1, fact: "Born during the French Revolution of 1789." },
    { q: "Union Jack belongs to?", options: ["Australia", "USA", "United Kingdom", "Canada"], answer: 2, difficulty: 1, fact: "Three crosses combined. Wales isn't represented." },
    { q: "Which flag changes in wartime?", options: ["Philippines", "Thailand", "Israel", "Switzerland"], answer: 0, difficulty: 4, fact: "War: red on top. Peace: blue on top. Only nation with this rule." },
    { q: "Animal on Sri Lankan flag?", options: ["Elephant", "Tiger", "Lion", "Peacock"], answer: 2, difficulty: 2, fact: "Golden lion holds a sword. Four bo leaves symbolize Buddhism." },
    { q: "Which flag has an AK-47?", options: ["Afghanistan", "Mozambique", "Yemen", "Libya"], answer: 1, difficulty: 3, fact: "Only national flag with a modern firearm." },
    { q: "Japan's flag design?", options: ["50 stars", "Red circle", "Three stripes", "Green crescent"], answer: 1, difficulty: 1, fact: "Red circle = sun. Japan means 'origin of the sun.'" },
    { q: "Oldest flag still in use?", options: ["UK", "Denmark", "France", "Japan"], answer: 1, difficulty: 3, fact: "Dannebrog dates to 1219 — over 800 years old." },
    { q: "Stars on Chinese flag?", options: ["1", "4", "5", "6"], answer: 2, difficulty: 2, fact: "Large star = Communist Party. Four small = four social classes." },
    { q: "Cedar tree flag?", options: ["Lebanon", "Syria", "Iraq", "Jordan"], answer: 0, difficulty: 2, fact: "Cedar of Lebanon is mentioned 75 times in the Bible." },
  ],
  "Bollywood 90s": [
    { q: "Who directed DDLJ?", options: ["Yash Chopra", "Aditya Chopra", "Sooraj Barjatya", "Karan Johar"], answer: 1, difficulty: 1, fact: "Aditya was 23. DDLJ ran at Maratha Mandir for 25+ years." },
    { q: "Which SRK film has 'Tujhe Dekha Toh'?", options: ["Kuch Kuch Hota Hai", "DDLJ", "Dil To Pagal Hai", "Mohabbatein"], answer: 1, difficulty: 1, fact: "The mustard field became so iconic Punjab Tourism promotes the actual fields." },
    { q: "Prem in Hum Aapke Hain Koun?", options: ["Aamir", "Shah Rukh", "Salman", "Akshay"], answer: 2, difficulty: 1, fact: "14 songs, almost no conflict. Still highest grosser of 1994." },
    { q: "Which film has 'Chaiyya Chaiyya'?", options: ["Dil Se", "Bombay", "Roja", "Taal"], answer: 0, difficulty: 1, fact: "SRK and Malaika danced on a moving train. Minimal safety." },
    { q: "Who directed Lagaan?", options: ["Rakeysh Mehra", "Ashutosh Gowariker", "Rajkumar Hirani", "Farhan Akhtar"], answer: 1, difficulty: 2, fact: "Oscar-nominated. The cricket match was filmed over 20 days." },
    { q: "Who composed Rangeela's music?", options: ["A.R. Rahman", "Anu Malik", "Nadeem-Shravan", "Vishal-Shekhar"], answer: 0, difficulty: 2, fact: "Sold over 10 million copies. Introduced electronic sound to Bollywood." },
    { q: "Lead actresses in Kuch Kuch Hota Hai?", options: ["Madhuri only", "Kajol only", "Kajol and Rani", "Aishwarya"], answer: 2, difficulty: 2, fact: "Karan Johar's debut. Inspired by American teen comedies." },
    { q: "Which 90s film has 'Ek Ladki Ko Dekha'?", options: ["1942: A Love Story", "Dil Se", "Pardes", "Bombay"], answer: 0, difficulty: 2, fact: "R.D. Burman composed it shortly before his death." },
    { q: "Who directed Border (1997)?", options: ["J.P. Dutta", "Anil Sharma", "Rakesh Roshan", "Subhash Ghai"], answer: 0, difficulty: 2, fact: "Based on the 1971 Battle of Longewala." },
    { q: "In DDLJ, SRK's famous dialogue begins with?", options: ["Senorita", "Bade bade deshon mein", "Palat", "Raj naam hai mera"], answer: 1, difficulty: 1, fact: "'Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai.'" },
    { q: "Who played villain in Baazigar?", options: ["Akshay", "Shah Rukh Khan", "Salman", "Aamir"], answer: 1, difficulty: 3, fact: "SRK played a villain who kills. Considered career suicide — became a hit." },
    { q: "Amitabh's comeback film?", options: ["Mohabbatein", "KBC", "Baghban", "Black"], answer: 0, difficulty: 3, fact: "After near-bankruptcy. Then KBC made him a TV icon." },
    { q: "Which actress was in both HAHK and DDLJ?", options: ["Kajol", "Madhuri", "Juhi", "None — different casts"], answer: 3, difficulty: 4, fact: "HAHK had Madhuri; DDLJ had Kajol. No shared leads." },
  ],
  "Olympics": [
    { q: "How often are Summer Olympics?", options: ["Every 2 years", "3 years", "4 years", "5 years"], answer: 2, difficulty: 1, fact: "2020 Tokyo was held in 2021 — first ever postponement." },
    { q: "First modern Olympics?", options: ["Paris", "Athens", "London", "Rome"], answer: 1, difficulty: 2, fact: "Athens 1896: 241 athletes, 14 nations. Now 10,000+ from 200+ nations." },
    { q: "Five Olympic rings represent?", options: ["5 sports", "5 continents", "5 founders", "5 values"], answer: 1, difficulty: 1, fact: "Every national flag contains at least one Olympic color." },
    { q: "Most decorated Olympian?", options: ["Usain Bolt", "Michael Phelps", "Carl Lewis", "Latynina"], answer: 1, difficulty: 1, fact: "28 medals (23 gold). More golds than 180 countries have ever won total." },
    { q: "Olympic motto?", options: ["Stronger Together", "Citius Altius Fortius", "Unity in Sport", "Peace Through Competition"], answer: 1, difficulty: 2, fact: "'Faster, Higher, Stronger.' 'Together' was added in 2021." },
    { q: "Sport removed after 2020 debut?", options: ["Wrestling", "Baseball", "Karate", "Squash"], answer: 2, difficulty: 3, fact: "Karate debuted AND was removed. Replaced by breakdancing for Paris 2024." },
    { q: "Who lit Barcelona 1992 flame?", options: ["Archer with flaming arrow", "Runner", "Gymnast", "Swimmer"], answer: 0, difficulty: 3, fact: "The arrow actually missed — but the pre-lit cauldron ignited anyway." },
    { q: "India's first individual Olympic gold?", options: ["Milkha Singh", "Abhinav Bindra", "Sushil Kumar", "Neeraj Chopra"], answer: 1, difficulty: 2, fact: "10m air rifle, Beijing 2008. India's first individual gold in 108 years." },
    { q: "When did women first compete?", options: ["1896", "1900", "1912", "1920"], answer: 1, difficulty: 3, fact: "Paris 1900: 22 women among 997 athletes. Full equality took a century." },
    { q: "Who boycotted 1980 Moscow Olympics?", options: ["China", "USSR", "USA", "Germany"], answer: 2, difficulty: 2, fact: "65 countries boycotted over Afghanistan. USSR boycotted LA 1984 in return." },
    { q: "How many Usain Bolt golds?", options: ["6", "7", "8", "9"], answer: 2, difficulty: 2, fact: "8 across 3 Olympics. Lost one due to teammate's doping." },
    { q: "Which city hosted both Summer and Winter?", options: ["Paris", "Tokyo", "Beijing", "London"], answer: 2, difficulty: 2, fact: "Beijing: Summer 2008 and Winter 2022 — only city to host both." },
    { q: "Youngest Olympic gold medalist?", options: ["Nadia", "Momiji Nishiya", "Marjorie Gestring", "Olga Korbut"], answer: 2, difficulty: 4, fact: "Marjorie Gestring: diving gold at Berlin 1936, age 13 years 268 days." },
  ],
};

const ROOM_NAMES = {
  "General Knowledge": ["Einstein's Lab", "Da Vinci's Studio", "Curie's Vault", "Newton's Study"],
  "Marvel / MCU": ["Stark Tower", "Wakanda Arena", "Asgard Hall", "Avengers HQ"],
  "Sacred Games": ["Gaitonde's Den", "Mumbai Underbelly", "Sartaj's Beat", "Trivedi Ashram"],
  "Cricket": ["Eden Gardens", "Lord's Pavilion", "Wankhede Stand", "Chinnaswamy Bowl"],
  "Game of Thrones": ["Winterfell Hall", "King's Landing", "Dragonstone Keep", "Castle Black"],
  "World Flags": ["Atlas Chamber", "UN Assembly", "Embassy Row", "Globe Room"],
  "Friends": ["Central Perk", "Monica's Apt", "Joey's Recliner", "Phoebe's Stage"],
  "Indian Independence": ["Sabarmati Ashram", "Dandi Road", "Red Fort Gate", "Azad Maidan"],
  "Football / Soccer": ["Camp Nou", "Bernabéu Arena", "Anfield Road", "Old Trafford"],
  "Scam 1992": ["Dalal Street", "BSE Trading Floor", "Bull Ring", "Mehta's Office"],
  "World Capitals": ["Summit Hall", "Capitol Room", "Parliament Ring", "Ambassador's Suite"],
  "The Family Man": ["TASC HQ", "Safe House Alpha", "Chellam's Library", "Ops Room"],
  "Disney Movies": ["Magic Kingdom", "Enchanted Castle", "Pride Rock", "Agrabah Arena"],
  "Harry Potter": ["Great Hall", "Room of Requirement", "Dumbledore's Office", "Diagon Alley"],
  "Bollywood 90s": ["Maratha Mandir", "Film City Ring", "YRF Hall", "Filmfare Stage"],
  "Panchayat": ["Phulera Office", "Sachiv's Desk", "Gram Sabha Ring", "Pradhan Pati Hall"],
  "The Office (US)": ["Dunder Mifflin", "Conference Room B", "The Annex", "Dwight's Farm"],
  "Internet Memes": ["Meme Factory", "Viral Vault", "Doge's Palace", "Comment Section"],
  "Famous Logos": ["Brand Central", "Logo Lab", "Design Studio", "Trademark Hall"],
  "Olympics": ["Olympic Village", "Medal Podium", "Torch Relay", "Stadium One"],
};

const TOPIC_ICONS = {
  "General Knowledge": "🧠", "Marvel / MCU": "🦸", "Sacred Games": "🔱",
  "Cricket": "🏏", "Game of Thrones": "⚔️", "World Flags": "🏳️",
  "Friends": "☕", "Indian Independence": "🇮🇳", "Football / Soccer": "⚽",
  "Scam 1992": "📈", "World Capitals": "🌍", "The Family Man": "🕵️",
  "Disney Movies": "🏰", "Harry Potter": "⚡", "Bollywood 90s": "🎬",
  "Panchayat": "🏡", "The Office (US)": "📎", "Internet Memes": "🌐",
  "Famous Logos": "™️", "Olympics": "🏅",
};

module.exports = { QUESTIONS, ROOM_NAMES, TOPIC_ICONS };
